name: release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Packages
        working-directory: ./
        run: cp -r packages rmt_webserver && tar zvcf rmt_webserver.tar.gz rmt_webserver
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}